version: '3'
services:
  python-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - frontend

networks:
  webnet:
    driver: bridge